// The ten public-site templates. Each is a combination of layout variants
// (nav, hero, cards, section titles, gallery) and design tokens (colors, fonts).
// Ids must match backend TEMPLATE_IDS (app/modules/super_admin/schemas.py).

export const THEMES = [
  {
    id: "classic",
    name: "Classic Heritage",
    tagline: "Timeless navy and gold, for colleges with a legacy.",
    audience: "Autonomous & university colleges",
    fonts: { heading: "'Playfair Display', Georgia, serif", body: "'Source Sans 3', system-ui, sans-serif", google: ["Playfair+Display:wght@600;700;800", "Source+Sans+3:wght@400;600"] },
    colors: { primary: "#1e3a8a", onPrimary: "#ffffff", accent: "#c8a24a", bg: "#fbf8f1", surface: "#ffffff", text: "#1f2937", muted: "#6b7280", border: "#e8e1d0" },
    nav: "centered",
    hero: "slider",
    cards: "classic",
    titles: "ornament",
    gallery: "grid",
    decoration: "none",
  },
  {
    id: "modern",
    name: "Modern Minimal",
    tagline: "Clean white space and bold type. Lets your photos speak.",
    audience: "Any college",
    fonts: { heading: "'Inter', system-ui, sans-serif", body: "'Inter', system-ui, sans-serif", google: ["Inter:wght@400;500;700;800"] },
    colors: { primary: "#111827", onPrimary: "#ffffff", accent: "#2563eb", bg: "#ffffff", surface: "#f9fafb", text: "#111827", muted: "#6b7280", border: "#e5e7eb" },
    nav: "solid",
    hero: "split",
    cards: "flat",
    titles: "eyebrow",
    gallery: "masonry",
    decoration: "none",
  },
  {
    id: "vibrant",
    name: "Kids Play",
    tagline: "Bright, bubbly and friendly. Made for pre-primary and primary.",
    audience: "Degree & junior colleges",
    fonts: { heading: "'Baloo 2', 'Comic Sans MS', system-ui, sans-serif", body: "'Nunito', system-ui, sans-serif", google: ["Baloo+2:wght@600;700;800", "Nunito:wght@400;600;700"] },
    colors: { primary: "#f97316", onPrimary: "#ffffff", accent: "#8b5cf6", bg: "#fff7ed", surface: "#ffffff", text: "#1e293b", muted: "#64748b", border: "#fed7aa" },
    nav: "pill",
    hero: "playful",
    cards: "bubbly",
    titles: "wiggle",
    gallery: "polaroid",
    decoration: "blobs",
  },
  {
    id: "emerald",
    name: "Emerald Campus",
    tagline: "Fresh greens and nature tones for green campuses.",
    audience: "Residential & green campuses",
    fonts: { heading: "'Poppins', system-ui, sans-serif", body: "'Poppins', system-ui, sans-serif", google: ["Poppins:wght@400;500;600;700"] },
    colors: { primary: "#047857", onPrimary: "#ffffff", accent: "#84cc16", bg: "#f3faf6", surface: "#ffffff", text: "#14342b", muted: "#58756b", border: "#d3ebe0" },
    nav: "transparent",
    hero: "fullbleed",
    cards: "soft",
    titles: "underline",
    gallery: "grid",
    decoration: "waves",
  },
  {
    id: "royal",
    name: "Royal Academy",
    tagline: "Rich maroon and cream with a regal, formal feel.",
    audience: "Heritage & arts colleges",
    fonts: { heading: "'Cinzel', Georgia, serif", body: "'Lora', Georgia, serif", google: ["Cinzel:wght@600;700", "Lora:wght@400;600"] },
    colors: { primary: "#7f1d1d", onPrimary: "#fff7ed", accent: "#d4a373", bg: "#fdf6ec", surface: "#fffaf3", text: "#3b1f1f", muted: "#7c5e57", border: "#ecd9c3" },
    nav: "transparent",
    hero: "centered",
    cards: "classic",
    titles: "ornament",
    gallery: "framed",
    decoration: "none",
  },
  {
    id: "neon",
    name: "Tech Future",
    tagline: "Dark mode with electric gradients. Bold and futuristic.",
    audience: "Engineering & tech colleges",
    fonts: { heading: "'Space Grotesk', system-ui, sans-serif", body: "'Inter', system-ui, sans-serif", google: ["Space+Grotesk:wght@500;600;700", "Inter:wght@400;500"] },
    colors: { primary: "#22d3ee", onPrimary: "#0b1020", accent: "#a855f7", bg: "#0b1020", surface: "#121a33", text: "#e2e8f0", muted: "#94a3b8", border: "#1f2a4a" },
    dark: true,
    nav: "glass",
    hero: "gradient",
    cards: "glass",
    titles: "numbered",
    gallery: "masonry",
    decoration: "grid",
  },
  {
    id: "sunrise",
    name: "Sunrise",
    tagline: "Warm orange-to-pink sunrise gradients, cheerful and optimistic.",
    audience: "Any college",
    fonts: { heading: "'Montserrat', system-ui, sans-serif", body: "'Open Sans', system-ui, sans-serif", google: ["Montserrat:wght@600;700;800", "Open+Sans:wght@400;600"] },
    colors: { primary: "#e11d48", onPrimary: "#ffffff", accent: "#f59e0b", bg: "#fffaf5", surface: "#ffffff", text: "#27161c", muted: "#7a5a64", border: "#fde2d4" },
    nav: "transparent",
    hero: "gradient",
    cards: "soft",
    titles: "eyebrow",
    gallery: "grid",
    decoration: "waves",
  },
  {
    id: "ocean",
    name: "Ocean Breeze",
    tagline: "Calm blues and teals with flowing wave dividers.",
    audience: "Coastal & international campuses",
    fonts: { heading: "'Quicksand', system-ui, sans-serif", body: "'Nunito Sans', system-ui, sans-serif", google: ["Quicksand:wght@600;700", "Nunito+Sans:wght@400;600;700"] },
    colors: { primary: "#0369a1", onPrimary: "#ffffff", accent: "#14b8a6", bg: "#f0f9ff", surface: "#ffffff", text: "#0c2a3e", muted: "#4b6b80", border: "#cfe8f6" },
    nav: "solid",
    hero: "slider",
    cards: "soft",
    titles: "underline",
    gallery: "masonry",
    decoration: "waves",
  },
  {
    id: "editorial",
    name: "Editorial",
    tagline: "A magazine-style layout with big serif headlines.",
    audience: "Pharmacy & science colleges",
    fonts: { heading: "'DM Serif Display', Georgia, serif", body: "'DM Sans', system-ui, sans-serif", google: ["DM+Serif+Display", "DM+Sans:wght@400;500;700"] },
    colors: { primary: "#18181b", onPrimary: "#fafafa", accent: "#b45309", bg: "#faf9f6", surface: "#ffffff", text: "#18181b", muted: "#71717a", border: "#e4e4e7" },
    nav: "editorial",
    hero: "editorial",
    cards: "flat",
    titles: "rule",
    gallery: "masonry",
    decoration: "none",
  },
  {
    id: "split",
    name: "Bold Split",
    tagline: "Your college's identity pinned on the left, content scrolling on the right.",
    audience: "Management & modern campuses",
    fonts: { heading: "'Archivo', system-ui, sans-serif", body: "'Archivo', system-ui, sans-serif", google: ["Archivo:wght@400;600;800"] },
    colors: { primary: "#4338ca", onPrimary: "#ffffff", accent: "#facc15", bg: "#f8fafc", surface: "#ffffff", text: "#0f172a", muted: "#64748b", border: "#e2e8f0" },
    nav: "none",
    hero: "sidebar",
    cards: "sharp",
    titles: "numbered",
    gallery: "grid",
    decoration: "dots",
  },
];

// Every college can use these; the other templates are Pro (unlocked by ANV Soft Solutions).
// Must match FREE_TEMPLATES in backend/app/modules/super_admin/schemas.py.
export const FREE_TEMPLATES = ["classic", "modern"];

export const THEME_BY_ID = Object.fromEntries(THEMES.map((t) => [t.id, t]));

export function themeFor(id) {
  return THEME_BY_ID[id] ?? THEMES[0];
}
